max_name: 30
min_name: 5
min_password: 6
min_description: 10
max_for_limit: 5
per_page: 5
truncate_description: 90
description_event: 360
min_location: 15
update: "Update"
create: "Create"
per_page_album: 9
per_page_image: 12
new_description: 9
edit_description: 6
min_rate: 1
max_rate: 5
ratings: "Ratings"
round_float: 1
